### ISSUE TITLE
If I click the "Manage Accounts" button it just closes the dialog window.

### ISSUE THREAD

**Issue by LajamerrMittesdine** [fourtf/chatterino2#515]
Don't have a video of this at the moment.

But you just click the person icon, it brings up the mini-account menu dialog.

Try clicking the Manage Accounts button.

Just closes the mini-account menu dialog window. Nothing else happens.

Intended behavior is to bring up the full Settings dialog on the Accounts tab.

**Comment by fourtf** [comment]
Can't reproduce.

**Comment by DatGuy1** [comment]
I believe this was fixed here https://github.com/fourtf/chatterino2/commit/8b4f9d066e30cfc267c22982e9d3ac173e66e280

**Comment by LajamerrMittesdine** [comment]
I've compiled the latest commit. Still experiencing this issue. Maybe it's a Linux specific issue.

**Comment by fourtf** [comment]
despacito 2 ![](https://cdn.frankerfacez.com/emoticon/61496/1)

**Comment by ch-ems** [comment]
is [this](https://gfycat.com/DismalVillainousAmericanindianhorse) what you mean?

**Comment by LajamerrMittesdine** [comment]
Narrowed down this to https://github.com/fourtf/chatterino2/blob/master/src/widgets/accountswitchpopupwidget.cpp#L17-#L18

Before it use to be 
`this->setWindowFlags(Qt::FramelessWindowHint);`
Now it's
```
this->setWindowFlag(Qt::FramelessWindowHint);
this->setWindowFlag(Qt::WindowStaysOnTopHint);
```
Changing those lines to this fixes it for me. Not sure if this breaks anything for windows.
`this->setWindowFlags(Qt::FramelessWindowHint | Qt::WindowStaysOnTopHint);`

**Comment by LajamerrMittesdine** [comment]
Merged and fixed.

Closing.
