### ISSUE TITLE
Unable to interact with emote menu except resizing it

### ISSUE THREAD

**Issue by gapbl4** [fourtf/chatterino2#883]
Sometimes when I open emote menu I can only resize it and nothing else.
Doesn't affect every channel at once, only one or few.

Closing menu through taskbar doesn't help,
still can't click anything after reopening the menu.

![](https://i.imgur.com/QWOp9Rz.gif)

Moving emote menu to other screen with win+shift+arrow helps

**Comment by Ckath** [comment]
might be the same cause as #862, could test this by compiling from 22cf436, where that issue didnt exist yet.

**Comment by Ckath** [comment]
this issue, and most likely #862 as well are likely fixed by bd8fab7, as that fixes all the weird issues caused by not redrawing correctly. can probably close these now

**Comment by gapbl4** [comment]
still happens sometimes even though I'm on latest nightly build

**Comment by gapbl4** [comment]
ye, emotes no longer appear weirdly in the menu like they did in #862 , instead emote menu takes like 3 seconds to load the first time you open it

**Comment by pajlada** [comment]
Should be fixed in the latest nightly build. If this is still an issue, please open a new issue describing the issue. Thanks for the report!
